language: go
os:
  - linux
  - osx
go:
  # 1.8 is now best-effort; we recommend 1.9; we are starting to use type aliases in libraries
  # - 1.8
  - 1.9
  - "1.10"

go_import_path: k8s.io/kops

script:
  - make ci
